services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 10
      MEMORY: 3G
      ENABLE_RCON: "false"
      OPS: |
        PhilippsEchelon
        _Zedzee_
    ports:
      - "25565:25565"
      - "8123:8123"
    volumes:
      - /mnt/data:/data
    restart: unless-stopped
